In [2]:
import numpy as np
print("NumPy version:", np.__version__)

NumPy version: 2.4.1


In [ ]:
#creating array
a=np.array([1,2,3,4,5])
b=np.array([[1,2,3],[4,5,6],[7,8,9]])
c=np.array([[[1,2,3],[4,5,6]],[[8,9,10],[11,12,13]]])

print(a)
print(b)
print(c)
print(type(a),type(b))
print("Dimensions:",a.ndim,b.ndim)    #returns dimension of the array
print("Data Type:", b.dtype)         #returns data type of the array
print("Shape: ", c.shape)             #returns shape of the array ,eg. (2,2,3)
print("Size: ",c.size)                #returns number of elements



[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 8  9 10]
  [11 12 13]]]
<class 'numpy.ndarray'> <class 'numpy.ndarray'>
Dimensions: 1 2
Data Type: int64
Shape:  (2, 2, 3)
Size:  12


In [19]:
#acessing,indexin,filtering
print(a[1])
print(b[1,2])
print(c[1,1,2])
print(a[1:3])
print(b[0:2,1])  #1st index of element at 0 and 1 index
print(b[1,0:2])  #0:2 index of element at 1 index
print(a[a>=3])

2
6
13
[2 3]
[2 5]
[4 5]
[3 4 5]


In [ ]:
#special arrays,sequences,methods

#create array of specific dimension
d=np.array([1,4,9,16],ndmin=5)   #create array of 5 dimension
print(d)

#create array of specified data type
arr=np.array([1,2,3,4],dtype='S')
print(arr)

#converting data type of an existing array
newarr=arr.astype('i')   #create copy of the array with astype method
print(newarr)

#filing an array
e=np.full((3,3),7)    #full(size,number) - create (3,3) dimension array and fill it with 7 number
print(e)

f=np.zeros((3,5,2))   #create array of size (3,5,2) filled with 0
print(f)

g=np.ones((2,4,3))   #create array of size (2,4,3) filled with 1
print(g)

h=np.empty((2,4,3))   #create an empty array of size (1,2,3) 
print(h)              #it dosent intialize values like zero method ,it reserves space

i=np.arange(0,35,5)   #arrange(start,stop,step)
print(i)       #[ 0  5 10 15 20 25 30]

j=np.linspace(0,35,6)   #linspace(start,stop,hoe many values we want)
print(j)                 #[ 0.  7. 14. 21. 28. 35.]

l=np.array([1,4,9,16])
print(np.isnan(np.sqrt(l)))     #nan=not a number

print(np.isinf(np.array([10])/0))  #inf=infinity

print(np.random.randint(0,10))     #gives random number each time
print(np.random.randint(1,100,size=(3,3))) #generate array with given size with random numbers

[[[[[ 1  4  9 16]]]]]
[b'1' b'2' b'3' b'4']
[1 2 3 4]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]
  [0. 0.]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[ 0  5 10 15 20 25 30]
[ 0.  7. 14. 21. 28. 35.]
[False False False False]
[ True]
3
[[76 11  5]
 [ 6 25 26]
 [ 3 41 88]]


C:\Users\muska\AppData\Local\Temp\ipykernel_16556\1715579110.py:37: RuntimeWarning: divide by zero encountered in divide
  print(np.isinf(np.array([10])/0))  #inf=infinity


In [59]:
#Arithmetic

l1=[1,2,3,4,5]
l2=[1,4,9,16,25]
arr1= np.array(l1)
arr2=np.array(l2)
print(l1+l2)     #[1, 2, 3, 4, 5, 1, 4, 9, 16, 25]
print(arr1+arr2)  #[ 2  6 12 20 30]
print(arr1*5)
print(arr2/2)
print(arr1-2)
print(arr2**0.5)

z=np.array([10,20,30,40,50])
print("Mean: ",np.mean(z))
print("Std: ", np.std(z))
print("Min: ",np.min(z))
print("Max: ",np.max(z))
print("Sum: ",np.sum(z))

[1, 2, 3, 4, 5, 1, 4, 9, 16, 25]
[ 2  6 12 20 30]
[ 5 10 15 20 25]
[ 0.5  2.   4.5  8.  12.5]
[-1  0  1  2  3]
[1. 2. 3. 4. 5.]
Mean:  30.0
Std:  14.142135623730951
Min:  10
Max:  50
Sum:  150
