In [1]:
import numpy as np

In [5]:
#copy and view
#copy
orginal=np.array([1,2,3,4,6])
copy=orginal.copy()       #owns data 
copy[4]=5                 #changes made in copy !=changes in orgianl
print(orginal)
print(copy)

#view
view=orginal.view()      #dosent own data
view[4]=5                #changes made in view== changes in orginal
print(orginal)
print(view)

#check if array owns data
print(copy.base)        #owns data return NONE
print(view.base)        #dosent own data return array itself


[1 2 3 4 6]
[1 2 3 4 5]
[1 2 3 4 5]
[1 2 3 4 5]
None
[1 2 3 4 5]


In [ ]:
#reshaping array
arr=np.arange(1,13)

#convert 1D to 2D
arr1=arr.reshape(3,4)
print(arr1)

#convert 1D to 3D
arr2=arr.reshape(2,2,3)
print(arr2)

#unknown dimension
arr3=arr.reshape(2,2,-1)   #numpy itself calculates the unknown dimension
print(arr3)

#flattening array (converting to 1D)
arr4=arr3.reshape(-1)
#or arr4=arr.flatten()
print(arr4)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [30]:
#iterating through array
arr1=np.array([1,2,3,4,5])
arr2=np.array([[1,2,3],[4,5,6]])
arr3=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for x in arr1:
    print(x)

for x in arr2:
    for y in x:
        print(y)
#or
for x in np.nditer(arr2):
    print(x)

for x in arr3:
    for y in x:
        for z in y:
            print(z)
#or
for x in np.nditer(arr3):
    print(x)

for x in np.nditer(arr2[:,::2]):
    print(x)



1
2
3
4
5
1
2
3
4
5
6
1
2
3
4
5
6
1
2
3
4
5
6
7
8
9
10
11
12
1
2
3
4
5
6
7
8
9
10
11
12
1
3
4
6


In [ ]:
#joining  and splitting arrays
#concatenate          #join along existing axis -no new dimension
a = np.array([1,2,3])
b = np.array([4,5,6])
np.concatenate([a,b]) 

a1 = np.array([[1,2],[3,4]])
b1 = np.array([[5,6],[7,8]])
np.concatenate([a1,b1],axis=1) #array([[1, 2, 5, 6],   #join columns
                                    #[3, 4, 7, 8]]
np.concatenate([a1,b1],axis=0)     #join rows
#array([[1, 2],
       #[3, 4],
       #[5, 6],
       #[7, 8]])

#stack()      #creates new dimension
np.stack([a,b])
#array([[1, 2, 3],
       #[4, 5, 6]])
np.stack([a,b],axis=1)
#array([[1, 4],
       #[2, 5],
       #[3, 6]])

#hstack   stack along rows
np.hstack([a1,b1])
#array([[1, 2, 5, 6],
       #[3, 4, 7, 8]])

#vstack   stack along columns
np.vstack([a1,b1])
#array([[1, 2],
       #[3, 4],
       #[5, 6],
       #[7, 8]])

#dstack    stack along depth(height)
np.dstack([a1,b1])
# array([[[1, 5],
#         [2, 6]],

#        [[3, 7],
#         [4, 8]]])

#splitting arrays
arr=np.array([1,2,3,4,5,6,7,8])
#array_split
newarr=np.array_split(arr,2)  #adjusts if elemnts less than required
print(newarr)
print(newarr[0])
print(newarr[1])

#split
newarr2=np.split(arr,2)    #gives error if elemnts less than required
print(newarr2)




[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
[1 2 3 4]
[5 6 7 8]
[array([1, 2, 3, 4]), array([5, 6, 7, 8])]
